# Generated by Django 2.1.10 on 2020-07-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_auto_20200705_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('destinations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.Destination')),
            ],
        ),
    ]
